---

- name: automating nexus switches
  hosts: spine
  connection: local
  gather_facts: no

  tasks:
    - name: default all Ethernet interfaces and remove all SVIs/portchannel/loopback interfaces for this test/demo
      nxapi_interface: interface=all state=absent host={{ inventory_hostname }}

    - name: get rid of all VLANs for this test/demo
      nxapi_vlan: vlan_id="2-3000" state=absent host={{ inventory_hostname }}


